version: '3'

services:
  # Example of running multiple instances with different configurations
  # To start a specific instance:
  # CONFIG_PATH=configs/instance1.env docker compose up instance1
  
  # Instance with all tools enabled (for testing)
  test:
    image: qs:main
    env_file: configs/test.env
    ports:
      - "8000:8000"
    restart: always

  # Template for production instances (commented out)
  # instance1:
  #   image: qs:main
  #   env_file: ${CONFIG_PATH}
  #   ports:
  #     - "8001:8000"
  #   restart: always
  
  # instance2:
  #   image: qs:main
  #   env_file: ${CONFIG_PATH}
  #   ports:
  #     - "8002:8000"
  #   restart: always

  # Default development instance
  app:
    image: qs:main
    env_file: configs/template.env
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    restart: always
