services:
  # Example of running multiple instances with different configurations
  # To start a specific instance:
  # CONFIG_PATH=configs/instance1.env docker compose up instance1

  # Instance with all tools enabled (for testing)
  # test:
  #   image: qs:main
  #   env_file: configs/.env.test
  #   ports:
  #     - "8000:8000"
  #   restart: always

  # Template for production instances (commented out)
  latest:
    image: qs:ethdenver
    env_file: configs/.env.latest
    ports:
      - "33333:3000"
      - "8000:8000"
    restart: always

  dimo:
    image: qs:ethdenver
    env_file: configs/.env.dimo
    ports:
      - "33334:3000"
      - "8001:8000"
    restart: always
