export enum ToolName {
  NEWS = "news",
  WEATHER_CURRENT = "weather-current",
  WEATHER_FORECAST = "weather-forecast",
  DEPIN_METRICS = "depin-metrics",
  DEPIN_PROJECTS = "depin-projects",
  L1DATA = "l1data",
  DIMO = "dimo",
  NUCLEAR = "nuclear",
  MAPBOX = "mapbox",
  LUMA = "luma",
  THIRDWEB = "thirdweb",
  CMC = "cmc",
  DEFILLAMA = "defillama",
  ASK_SPECIALTY = "ask_specialty",
}
